---
# BY ITSTOXICGG
# LDFxConfig V1.0
# BY ITSTOXICGG
# ----------
# Fly-Config
  # The below config allows the plugin to reset flight mode when joining the server
  JFlyReset: true
  # The below config allows you to send a message to the player when they disable fly
  FDMessage: "§cFlyMode is off!"
  # The below config enables multi-world settings (OPTIONS: on and off)
  FLY-MW: "off"
  # List all the worlds that fly would work on!
  worlds:
  - "world"
# EndOfFlyConfig
# Ping-Config
  tps-check: 20

  #Choose the ping of when a player should be kicked, (I recommend you put it above 2000)
  ping-kick: 2000

  #Choose the kick message when a player is kicked for exceeding the ping limit
  kick-message: "§7You were kicked, this was caused by high ping!"
# EndOfPing-Config
# Bow-Config
  enable-sound: true # Enable sound ?
  sound-volume: 1
  sound-pitch: 1
  sound-name: "random.orb"

  enable-message: true # Enable message ?
  hit-message: "§c{name} §7(§aHP: §e{hp}§7)"
 
  enable-popup: false  # Enable popup ?
  hit-popup: "§c{name} §7(§aHP: §e{hp}§7)"

  enable-tip: false  # Enable tip ?
  hit-tip: "§c{name} §7(§aHP: §e{hp}§7)"
# EndOfBow-Config
# AntiVoid-Config
  enabled-worlds: []

  disabled-worlds: []

  use-default-world: false
# EndOfAntiVoid-Config
# EnderPearlCoolDown-Config
cooldown: 5
message: "you must wait {cooldown}s to use an enderpearl again!"
# EndOfEnderPearlCoolDown-Config
# LobbyCore-Config
  #Items 1 | Compass
  item1-name: "§r§cReport Player" # Name Items
  item1-cmd: "report" # Your Commands

  #Items 2 | Name Tag
  item2-name: "§r§aTeleporter" # Name Items
  item2-cmd: "gui" # Your Commands

  #Items 4 | Enchanted Book
  item3-name: "§r§dSocial Menu §7[Use]" # Name Items
  item3-cmd: "socialmenu" # Your Commands
# EndOfLobbyCore-Config
# GameUI-Config
  #GameUI-1
  GameUi-1: "thebridge random"
  
  #GameUI-2
  GameUi-2: "bedwars random"
  
  #GameUI-3
  GameUi-3: "skywars random"
# EndOfGameUI-Config
...
